### PR TITLE
Fix crashes when Y > 255

### PR DESCRIPTION
**Pull request by DrParadox7**
Game crashes when Smooth Entity Light is applied at heights above 255

### CODE REVIEW

**Comment by DrParadox7** [comment]
Crash Reports:
[crash-2024-06-03_01.46.27-client.txt](https://github.com/user-attachments/files/15527425/crash-2024-06-03_01.46.27-client.txt)
[crash-2024-06-03_01.48.56-client.txt](https://github.com/user-attachments/files/15527426/crash-2024-06-03_01.48.56-client.txt)
[crash-2024-06-02_17.30.16-client.txt](https://github.com/user-attachments/files/15527428/crash-2024-06-02_17.30.16-client.txt)

**Comment by DrParadox7** [comment]
Fixes #21

**Comment by LakMoore** [comment]
Hello and Thanks @DrParadox7 
I think you are correct, there needs to be extra protection for out of bounds y values.  I think that was added in a later version but never back-ported into 1.7.10.  I've checked the latest code and the array is not accessed in the same way any more so the fix isn't required.  Thank you for the PR.

I'd be happy to merge https://github.com/LakMoore/Smooth-Entity-Light/pull/26/commits/7a78d3d3c2b698489a3af571d524b5dc3171c9d6 into the 1.7.10 branch.  If you could fix up the PR to only include the code changes in that commit.

But the other two commits are a little bit of a big ask.  That buildscript is horrid and looks like it has been copied over from someone else's project.   If that is what you need to get it to work locally that is fine, but that is not to my taste.   It is the changes to the buildscript here: https://github.com/LakMoore/Smooth-Entity-Light/pull/26/commits/5edf85367588dd44361607a9d4e93708194539f8  that caused the change in the method name (different mappings) here: https://github.com/LakMoore/Smooth-Entity-Light/pull/26/commits/87fe3bdad86fb1ad18182e0ff2bfc3734c46e634

**Comment by DrParadox7** [comment]
> Hello and Thanks @DrParadox7 I think you are correct, there needs to be extra protection for out of bounds y values. I think that was added in a later version but never back-ported into 1.7.10. I've checked the latest code and the array is not accessed in the same way any more so the fix isn't required. Thank you for the PR.
> 
> I'd be happy to merge [7a78d3d](https://github.com/LakMoore/Smooth-Entity-Light/commit/7a78d3d3c2b698489a3af571d524b5dc3171c9d6) into the 1.7.10 branch. If you could fix up the PR to only include the code changes in that commit.
> 
> But the other two commits are a little bit of a big ask. That buildscript is horrid and looks like it has been copied over from someone else's project. If that is what you need to get it to work locally that is fine, but that is not to my taste. It is the changes to the buildscript here: [5edf853](https://github.com/LakMoore/Smooth-Entity-Light/commit/5edf85367588dd44361607a9d4e93708194539f8) that caused the change in the method name (different mappings) here: [87fe3bd](https://github.com/LakMoore/Smooth-Entity-Light/commit/87fe3bdad86fb1ad18182e0ff2bfc3734c46e634)

Sure no problem. I've cleaned that up

**Pull request closed without merging**
